more hacking around with init script

diff --git a/templates/bsl_bootstrap.debian.init.erb b/templates/bsl_bootstrap.debian.init.erb
--- a/templates/bsl_bootstrap.debian.init.erb
+++ b/templates/bsl_bootstrap.debian.init.erb
@@ -32,21 +32,38 @@ do_start () {
   apt-get update -qy
 
   ssl_dir=$(puppet config print ssldir)
+  certfile="${ssl_dir}/certs/${TARGET_CERTNAME}.pem"
 
-  msg="## CURRENT SSL DIR CONTENTS: ls -lR $ssl_dir :\n$(ls -lR $ssl_dir)"
+  $PUPPET resource user puppet home='<%= scope.lookupvar('::puppet::dir') %>'
+
+  msg="## SETTING HOSTNAME ALIAS FOR ${TARGET_CERTNAME}"
   [ "$LOGFILE" != "syslog" ] && [ "$LOGFILE" != "console" ] && echo $msg >> $LOGFILE
   [ "$VERBOSE" != no ] && log_daemon_msg $msg
 
-  certfile="${ssl_dir}/certs/${TARGET_CERTNAME}.pem"
+  $PUPPET apply --logdest=$LOGFILE -e "host { '${TARGET_CERTNAME}': ip => '127.0.0.1', host_aliases => [$::hostname, $::fqdn] }"
+
+  <%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_service_facter_vars') -%> $PUPPET apply \
+    <%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_service_puppet_args') %> \
+    --hiera_config=/etc/puppetlabs/code/bsl_bootstrap/hiera.yaml \
+    --certname=$TARGET_CERTNAME \
+    --environment='<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::environment') %>' \
+    --logdest=$LOGFILE \
+    -e 'class { '\''<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::bootstrap_classname') %>'\'': }'
+  retval=$?
+
+  for f in $(find /opt/puppetlabs/bin -type l -or -type f); do
+    ln -sf $(readlink -f "$f") /usr/bin/$(basename "$f")
+  done
+
+  if [ $retval -eq 0 ]; then
+    msg="## PROVISIONING SUCCESSFUL @ $(date)"
+  else
+    msg="## PUPPET RUN FAILED (${retval}) @ $(date)"
+  fi
+  [ "$LOGFILE" != "syslog" ] && [ "$LOGFILE" != "console" ] && echo $msg >> $LOGFILE
+  [ "$VERBOSE" != no ] && log_daemon_msg $msg
 
   if [ ! -e $certfile ]; then
-    msg="## SETTING HOSTNAME ALIAS FOR ${TARGET_CERTNAME}"
-    [ "$LOGFILE" != "syslog" ] && [ "$LOGFILE" != "console" ] && echo $msg >> $LOGFILE
-    [ "$VERBOSE" != no ] && log_daemon_msg $msg
-
-    $PUPPET apply --logdest=$LOGFILE -e \
-    "host { '${TARGET_CERTNAME}': ip => '127.0.0.1', host_aliases => [$::hostname, $::fqdn] }"
-
     msg="## GENERATING CA CERTS via '${PUPPET} agent -t --certname=${TARGET_CERTNAME}'"
     [ "$LOGFILE" != "syslog" ] && [ "$LOGFILE" != "console" ] && echo $msg >> $LOGFILE
     [ "$VERBOSE" != no ] && log_daemon_msg $msg
@@ -69,41 +86,14 @@ do_start () {
 
     [ "$LOGFILE" != "syslog" ] && [ "$LOGFILE" != "console" ] && echo $msg >> $LOGFILE
     [ "$VERBOSE" != no ] && log_daemon_msg $msg
-
-    msg="## NEW SSL DIR CONTENTS: ls -lR $ssl_dir :\n$(ls -lR $ssl_dir)"
-    [ "$LOGFILE" != "syslog" ] && [ "$LOGFILE" != "console" ] && echo $msg >> $LOGFILE
-    [ "$VERBOSE" != no ] && log_daemon_msg $msg
   else
-    agent_retval=0
-    cert_retval=0
-
-    msg="## BSL_BOOTSTRAP Skipped running '${PUPPET} agent -t' to regenerate certs- $certfile exists"
+    msg="## CA CERT $certfile already exists"
     [ "$LOGFILE" != "syslog" ] && [ "$LOGFILE" != "console" ] && echo $msg >> $LOGFILE
     [ "$VERBOSE" != no ] && log_daemon_msg $msg
   fi
 
-  <%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_service_facter_vars') -%> $PUPPET apply \
-    <%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_service_puppet_args') %> \
-    --hiera_config=/etc/puppetlabs/code/bsl_bootstrap/hiera.yaml \
-    --certname=$TARGET_CERTNAME \
-    --environment='<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::environment') %>' \
-    --logdest=$LOGFILE \
-    -e 'class { '\''<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::bootstrap_classname') %>'\'': }'
-  retval=$?
 
-  for f in $(find /opt/puppetlabs/bin -type l -or -type f); do
-    ln -sf $(readlink -f "$f") /usr/bin/$(basename "$f")
-  done
-
-  if [ $retval -eq 0 ]; then
-    msg="## BSL_BOOTSTRAP PUPPET RUN ALL DONE (success) @ $(date)"
-  else
-    msg="## BSL_BOOTSTRAP PUPPET RUN FAILED (${retval}) @ $(date)"
-  fi
-  [ "$LOGFILE" != "syslog" ] && [ "$LOGFILE" != "console" ] && echo $msg >> $LOGFILE
-  [ "$VERBOSE" != no ] && log_daemon_msg $msg
-
-  log_end_msg $retval
+log_end_msg $retval
 }
 
 case "$1" in
