debugging

diff --git a/templates/puppetmaster/bsl-bootstrap-init_debian_init.erb b/templates/puppetmaster/bsl-bootstrap-init_debian_init.erb
--- a/templates/puppetmaster/bsl-bootstrap-init_debian_init.erb
+++ b/templates/puppetmaster/bsl-bootstrap-init_debian_init.erb
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 ### BEGIN INIT INFO
 # Provides:          bsl-bootstrap-init
@@ -24,28 +24,61 @@ PUPPET_LOGDEST='<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_s
 TARGET_CERTNAME='<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::target_certname') %>'
 
 do_start () {
-  log_use_fancy_output()
+  declare -i final_result=0
+  declare -i retval=0
 
-  log_progress_msg "## BSL_BOOTSTRAP STARTUP INIT BEGINS via ${PUPPET} @ $(date) target_certname=${TARGET_CERTNAME}" | tee -a $LOGFILE
+  log_begin_msg " BSL_BOOTSTRAP STARTUP INIT BEGINS via ${PUPPET} target_certname=${TARGET_CERTNAME}"
+  echo "# BSL_BOOTSTRAP STARTUP INIT BEGINS via ${PUPPET} @ $(date) target_certname=${TARGET_CERTNAME}" >> $LOGFILE
 
-  log_progress_msg "## running apt-get update" | tee -a $LOGFILE
+  log_progress_msg "Executing apt-get update"
+  echo "## executing apt-get update" >> $LOGFILE
   apt-get update -qy 2>&1 | tee -a $LOGFILE
+  retval=$PIPESTATUS[0]
+  final_result+=$retval
 
+  if [ $retval -eq 0 ]; then
+    log_success_msg "success!"
+    echo "## success!\n" >> $LOGFILE
+  else
+    log_failure_msg "failed ($retval)\n"
+    echo "## failed ($retval)\n" >> $LOGFILE
+  fi
+
+  log_progress_msg "Creating user for Puppet"
+  echo "## creating user for puppet" >> $LOGFILE
   <%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_service_facter_vars') -%> $PUPPET \
     resource --verbose --show_diff \
     user puppet ensure=present home='/etc/puppetlabs/code' \
     2>&1 | tee -a $LOGFILE
+  retval=$PIPESTATUS[0]
+  final_result+=$retval
 
-  log_progress_msg "## SETTING HOSTNAME ALIAS FOR ${TARGET_CERTNAME}" | tee -a $LOGFILE
+  if [ $retval -eq 0 ]; then
+    log_success_msg "success!"
+    echo "success!\n" >> $LOGFILE
+  else
+    log_failure_msg "failed ($retval)\n"
+    echo "## failed ($retval)\n" >> $LOGFILE
+  fi
 
+  log_progress_msg "Setting /etc/hosts alias for ${TARGET_CERTNAME}"
+  echo "## Setting /etc/hosts alias for ${TARGET_CERTNAME}"
   <%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_service_facter_vars') -%>  $PUPPET \
     apply --logdest=$PUPPET_LOGDEST --verbose --show_diff \
     -e "host { '${TARGET_CERTNAME}': ip => '127.0.0.1', host_aliases => [$::hostname, $::fqdn] }" \
     2>&1 | tee -a $LOGFILE
+  retval=$PIPESTATUS[0]
+  final_result+=$retval
 
-  retval=$?
+  if [ $retval -eq 0 ]; then
+    log_success_msg "success!"
+    echo "success!\n" >> $LOGFILE
+  else
+    log_failure_msg "failed ($retval)\n"
+    echo "## failed ($retval)\n" >> $LOGFILE
+  fi
 
-  log_progress_msg "## BSL_BOOTSTRAP INIT COMPLETE RESULT ($retval) @ $(date)" | tee -a $LOGFILE
+  log_end_msg $finalretval
 }
 
 case "$1" in
