development on init scripts

diff --git a/templates/puppetmaster/bsl-bootstrap-final_debian_init.erb b/templates/puppetmaster/bsl-bootstrap-final_debian_init.erb
--- a/templates/puppetmaster/bsl-bootstrap-final_debian_init.erb
+++ b/templates/puppetmaster/bsl-bootstrap-final_debian_init.erb
@@ -1,16 +1,18 @@
-#!/bin/sh
+#!/bin/bash
 
 ### BEGIN INIT INFO
 # Provides:          bsl-bootstrap-final
 # Required-Start:    $all
 # Required-Stop:
-# Should-Start:      bsl-bootstrap-init
+# Should-Start:      bsl-bootstrap-init cloud-final
 # Should-Stop:
 # Default-Start:     2 3 4 5
 # Default-Stop:
 # Short-Description: bsl_bootstrap final provisioning
 # Description:       Final startup Puppetmaster provisioning using bsl_bootstrap
 ### END INIT INFO
+
+set -o pipefail
 
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
@@ -22,42 +24,67 @@
 
 LOGFILE='<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_service_puppet_log') %>'
 PUPPET='<%= scope.lookupvar('bsl_bootstrap::puppet_binary') %>'
+PUPPET_LOGDEST='<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_service_puppet_logger') %>'
+PUPPET_ENVIRONMENT='<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::environment') %>'
 TARGET_CERTNAME='<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::target_certname') %>'
 
 do_start () {
-  log_begin_msg "## BSL_BOOTSTRAP FINAL PROVISIONING BEGINS via ${PUPPET} @ $(date) target_certname=${TARGET_CERTNAME}" | tee $LOGFILE
+  declare -i final_result=0
+  declare -i retval=0
+
+  log_begin_msg "BSL_BOOTSTRAP STARTUP FINAL BEGINS via ${PUPPET} target_certname=${TARGET_CERTNAME}" && log_end_msg 0
+  echo "# BSL_BOOTSTRAP STARTUP FINAL BEGINS via ${PUPPET} @ $(date) target_certname=${TARGET_CERTNAME}" >> $LOGFILE
 
   ssl_dir=$(puppet config print ssldir)
   certfile="${ssl_dir}/certs/${TARGET_CERTNAME}.pem"
   certname=$(puppet config print certname --environment='<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::environment') %>')
 
-  log_daemon_msg "## ssl_dir: $ssl_dir" >> $LOGFILE
-  log_daemon_msg "## certname: $certname" >> $LOGFILE
+  echo "## ssl_dir: $ssl_dir" >> $LOGFILE
+  echo "## certname: $certname" >> $LOGFILE
 
+  log_begin_msg 'Final bootstrap provisioning begins'
+  echo "
+## Final bootstrap provisioning begins via puppet apply certname=${TARGET_CERTNAME} environment=${PUPPET_ENVIRONMENT}" >> $LOGFILE
+
+  set -x
   <%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_service_facter_vars') -%> $PUPPET apply \
-    <%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_service_puppet_args') %> \
+    --show_diff --verbose --detailed-exitcodes \
     --hiera_config=/etc/puppetlabs/code/bsl_bootstrap/hiera.yaml \
     --certname=$TARGET_CERTNAME \
-    --environment='<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::environment') %>' \
+    --environment=$PUPPET_ENVIRONMENT \
     --logdest=$PUPPET_LOGDEST \
-    -e 'class { '\''<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::bootstrap_classname') %>'\'': }' \
+    -e 'class { '\''bsl_bootstrap::puppetmaster::setup'\'': }' \
     2>&1 | tee -a $LOGFILE
   retval=$?
+  set +x
 
-  new_certname=$(puppet config print certname --environment='<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::environment') %>')
-  log_daemon_msg "## new certname: $new_certname" >> $LOGFILE
+  if [ $retval -eq 0 ] || [ $retval -neq 1 ]; then
+    log_success_msg "success!"
+    echo "## ... success!!" >> $LOGFILE
+    log_end_msg 0
+  else
+    log_failure_msg "failed ($retval)"
+    echo "## puppet non-zero return ($retval)" >> $LOGFILE
+    final_result+=$retval
+    log_end_msg $retval
+  fi
+
+  new_certname=$(puppet config print certname --environment=$PUPPET_ENVIRONMENT)
+  echo "## new certname: $new_certname" >> $LOGFILE
 
   for f in $(find /opt/puppetlabs/bin -type l -or -type f); do
-    $(ln -svf $(readlink -f "$f") /usr/bin/$(basename "$f")) >> $LOGFILE 2>&1
+    echo $(ln -svf $(readlink -f "$f") /usr/bin/$(basename "$f")) >> $LOGFILE 2>&1
   done
 
   if [ $retval -neq 1 ]; then
-    log_daemon_msg "## PROVISIONING SUCCESSFUL @ $(date)" >> $LOGFILE
-    log_end_msg 0
+    echo "## PROVISIONING SUCCESSFUL @ $(date)
+" >> $LOGFILE
   else
-    log_daemon_msg "## PROVISIONING FAILED (${retval}) @ $(date)" >> $LOGFILE
-    log_end_msg $retval
+    echo "## PROVISIONING FAILED (${retval}) @ $(date)
+" >> $LOGFILE
   fi
+
+  exit $final_result
 }
 
 case "$1" in
diff --git a/templates/puppetmaster/bsl-bootstrap-init_debian_init.erb b/templates/puppetmaster/bsl-bootstrap-init_debian_init.erb
--- a/templates/puppetmaster/bsl-bootstrap-init_debian_init.erb
+++ b/templates/puppetmaster/bsl-bootstrap-init_debian_init.erb
@@ -2,8 +2,10 @@
 
 ### BEGIN INIT INFO
 # Provides:          bsl-bootstrap-init
-# Required-Start:    $local_fs $network $syslog cloud-init
+# Required-Start:    $local_fs $network $syslog
 # Required-Stop:
+# Should-Start:      cloud-init
+# Should-Stop:
 # Default-Start:     2 3 4 5
 # Default-Stop:
 # Short-Description: bsl_bootstrap early provisioning
@@ -23,70 +25,76 @@ set -o pipefail
 LOGFILE='<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_service_puppet_log') %>'
 PUPPET='<%= scope.lookupvar('bsl_bootstrap::puppet_binary') %>'
 PUPPET_LOGDEST='<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_service_puppet_logger') %>'
+PUPPET_ENVIRONMENT='<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::environment') %>'
 TARGET_CERTNAME='<%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::target_certname') %>'
 
 do_start () {
   declare -i final_result=0
   declare -i retval=0
 
-  log_begin_msg " BSL_BOOTSTRAP STARTUP INIT BEGINS via ${PUPPET} target_certname=${TARGET_CERTNAME}"
+  log_begin_msg "BSL_BOOTSTRAP STARTUP INIT BEGINS via ${PUPPET} target_certname=${TARGET_CERTNAME}" && log_end_msg 0
   echo "# BSL_BOOTSTRAP STARTUP INIT BEGINS via ${PUPPET} @ $(date) target_certname=${TARGET_CERTNAME}" >> $LOGFILE
 
-  log_progress_msg "Executing apt-get update"
+  log_begin_msg "Executing apt-get update"
   echo "
-## executing apt-get update
-" >> $LOGFILE
+## executing apt-get update" >> $LOGFILE
   apt-get update -qy 2>&1 | tee -a $LOGFILE
   retval=$?
   final_result+=$retval
 
   if [ $retval -eq 0 ]; then
     log_success_msg "success!"
+    echo "## ... success!!" >> $LOGFILE
   else
     log_failure_msg "failed ($retval)"
     echo "## apt-get non-zero return ($retval)" >> $LOGFILE
   fi
+  log_end_msg $retval
 
-  log_progress_msg "Creating user for Puppet"
+  log_begin_msg "Creating user for Puppet"
   echo "
-
-## creating user for puppet
-" >> $LOGFILE
-
+## creating user for puppet" >> $LOGFILE
+  
+  set -x
   <%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_service_facter_vars') -%> $PUPPET \
-    resource --verbose --show_diff \
-    user puppet ensure=present home='/etc/puppetlabs/code' \
-    2>&1 | tee -a $LOGFILE
+    resource --verbose --environment=$PUPPET_ENVIRONMENT \
+      --hiera_config=/etc/puppetlabs/code/bsl_bootstrap/hiera.yaml \
+      user puppet ensure=present home='/etc/puppetlabs/code' \
+      2>&1 | tee -a $LOGFILE
   retval=$?
-  final_result+=$retval
+  set +x
 
   if [ $retval -eq 0 ]; then
     log_success_msg "success!"
-    echo "success!" >> $LOGFILE
+    echo "## ... success!!" >> $LOGFILE
+    log_end_msg 0
   else
     log_failure_msg "failed ($retval)"
-    echo "## failed ($retval)" >> $LOGFILE
+    echo "## puppet non-zero return ($retval)" >> $LOGFILE
+    final_result+=$retval
   fi
+  log_end_msg $retval
 
-  log_progress_msg "Setting /etc/hosts alias for ${TARGET_CERTNAME}"
+  log_begin_msg "Setting /etc/hosts alias for ${TARGET_CERTNAME}"
   echo "
-
-## Setting /etc/hosts alias for ${TARGET_CERTNAME}
-" >> $LOGFILE
+## Setting /etc/hosts alias for ${TARGET_CERTNAME}" >> $LOGFILE
+  set -x
   <%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_service_facter_vars') -%>  $PUPPET \
-    apply --logdest=$PUPPET_LOGDEST --verbose --show_diff \
+    apply --logdest=$PUPPET_LOGDEST --environment=$PUPPET_ENVIRONMENT --verbose --show_diff \
     -e "host { '${TARGET_CERTNAME}': ip => '127.0.0.1', host_aliases => [$::hostname, $::fqdn] }" \
     2>&1 | tee -a $LOGFILE
   retval=$?
-  final_result+=$retval
+  set +x
 
   if [ $retval -eq 0 ]; then
     log_success_msg "success!"
-    echo "success!" >> $LOGFILE
+    echo "## ... success!!" >> $LOGFILE
   else
     log_failure_msg "failed ($retval)"
-    echo "## failed ($retval)" >> $LOGFILE
+    echo "## puppet non-zero return ($retval)" >> $LOGFILE
+    final_result+=$retval
   fi
+  log_end_msg $retval
 
   if [ $final_result -gt 0 ]; then
     echo "# BSL_BOOTSTRAP INIT FAIL (${final_result})
@@ -96,7 +104,7 @@ do_start () {
 " >> $LOGFILE
   fi
 
-  log_end_msg $finalretval
+  exit $final_result
 }
 
 case "$1" in
