Adding puppet agent -t run to init script

diff --git a/templates/puppetmaster/bsl-bootstrap-final_debian_init.erb b/templates/puppetmaster/bsl-bootstrap-final_debian_init.erb
--- a/templates/puppetmaster/bsl-bootstrap-final_debian_init.erb
+++ b/templates/puppetmaster/bsl-bootstrap-final_debian_init.erb
@@ -77,10 +77,35 @@ do_start () {
     echo " - $(ln -svf $(readlink -f "$f") /usr/bin/$(basename "$f"))" >> $LOGFILE 2>&1
   done
 
-  if [ $final_result -ne 1 ]; then
+  log_begin_msg "Attempting puppet agent -t"
+  echo "
+## Attempting puppet agent -t run" >> $LOGFILE
+
+  set -x
+  <%= scope.lookupvar('bsl_bootstrap::puppetmaster::config::init_service_facter_vars') -%> $PUPPET agent \
+    --test --noop 2>&1 | tee -a $LOGFILE
+  retval=$?
+  set +x
+
+  if [ $retval -ne 1 ]; then
+    log_success_msg "success!"
+    echo "## ... success!!" >> $LOGFILE
+    log_end_msg 0
+  else
+    log_failure_msg "failed (ignoring)" $retval
+    echo "## puppet agent non-zero return ($retval) - ignoring" >> $LOGFILE
+    log_end_msg $retval
+  fi
+
+  log_begin_msg "Provisioning"
+  if [ $final_result -eq 0 ]; then
+    log_success_msg "successful"
+    log_end_msg 0
     echo "## PROVISIONING SUCCESSFUL @ $(date)
 " >> $LOGFILE
   else
+    log_failure_msg "failed"
+    log_end_msg 1
     echo "## PROVISIONING FAILED (${retval}) @ $(date)
 " >> $LOGFILE
   fi
